// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using la_mia_pizzeria_static.DB;

#nullable disable

namespace la_mia_pizzeria_static.Migrations
{
    [DbContext(typeof(PizzaContext))]
    [Migration("20220715144600_IngredientSeed2")]
    partial class IngredientSeed2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.Property<int>("IngredientsId")
                        .HasColumnType("int");

                    b.Property<int>("PizzeId")
                        .HasColumnType("int");

                    b.HasKey("IngredientsId", "PizzeId");

                    b.HasIndex("PizzeId");

                    b.ToTable("IngredientPizza");
                });

            modelBuilder.Entity("la_mia_pizzeria_static.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "pomodoro"
                        },
                        new
                        {
                            Id = 2,
                            Name = "mozzarella"
                        },
                        new
                        {
                            Id = 3,
                            Name = "basilico"
                        },
                        new
                        {
                            Id = 4,
                            Name = "prosciutto"
                        },
                        new
                        {
                            Id = 5,
                            Name = "pomodoro ciliegino"
                        },
                        new
                        {
                            Id = 6,
                            Name = "mozarella di bufala"
                        },
                        new
                        {
                            Id = 7,
                            Name = "olive"
                        });
                });

            modelBuilder.Entity("la_mia_pizzeria_static.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizze");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Pomodoro, mozzarella, basilico",
                            ImageUrl = "~/img/margherita.png",
                            Name = "Margherita",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pomodoro, mozzarella, prosciutto",
                            ImageUrl = "~/img/prosciutto.png",
                            Name = "Prosciutto",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pomodoro ciliegino, mozarella di bufala, olive",
                            ImageUrl = "~/img/bufalina.jpg",
                            Name = "Bufalina",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Pomodoro, mozzarella, prosciutto",
                            ImageUrl = "https://www.pizzaventura.com/wp-content/uploads/2020/03/calzone.jpg",
                            Name = "Calzone",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Pomodoro, mozzarella, basilico",
                            ImageUrl = "~/img/margherita.png",
                            Name = "Margherita2",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Pomodoro, mozzarella, prosciutto",
                            ImageUrl = "~/img/prosciutto.png",
                            Name = "Prosciutto2",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Pomodoro ciliegino, mozarella di bufala, olive",
                            ImageUrl = "~/img/bufalina.jpg",
                            Name = "Bufalina2",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Pomodoro, mozzarella, prosciutto",
                            ImageUrl = "https://www.pizzaventura.com/wp-content/uploads/2020/03/calzone.jpg",
                            Name = "Calzone2",
                            Price = 12.99m
                        });
                });

            modelBuilder.Entity("IngredientPizza", b =>
                {
                    b.HasOne("la_mia_pizzeria_static.Models.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("la_mia_pizzeria_static.Models.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
